name: Mobile Automation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Appium
        run: |
          npm install -g appium
          appium --version

      - name: Install UiAutomator2
        run: |
          appium driver install uiautomator2
          appium driver list --installed

      - name: Enable KVM
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-kvm
          sudo adduser $USER kvm
          sudo chown $USER /dev/kvm

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          target: google_apis
          arch: x86_64
          profile: pixel_2
          emulator-options: -no-window -no-audio -no-boot-anim
          disable-animations: true
          script: adb devices

      - name: Start Appium
        run: |
          nohup appium --address 127.0.0.1 --port 4723 > appium.log 2>&1 &
          sleep 5
          curl http://127.0.0.1:4723/status

      - name: Check Android device
        run: |
          adb devices

      - name: Run Maven tests
        run: mvn clean test