name: Mobile Automation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Appium
        run: |
          npm install -g appium
          appium driver install uiautomator2
          appium --version
          appium driver list --installed

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Create Android emulator
        run: |
          sdkmanager "platform-tools" "emulator" \
            "platforms;android-35" \
            "system-images;android-35;google_apis;x86_64"
          
          echo "no" | avdmanager create avd \
            -n test-emulator \
            -k "system-images;android-35;google_apis;x86_64" \
            --force
          
          emulator -list-avds

      - name: Start Android emulator
        timeout-minutes: 5
        run: |
          echo "Starting emulator..."
          
          nohup emulator \
          -avd test-emulator \
          -no-window \
          -no-audio \
          -no-boot-anim \
          -no-snapshot \
          -gpu swiftshader_indirect \
          > emulator.log 2>&1 &
          
          echo "Waiting for device..."
          
          adb wait-for-device
          
          echo "ADB detected device"
          
          for i in {1..60}; do
          BOOT_COMPLETED=$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')

          echo "Boot status: $BOOT_COMPLETED"

          if [ "$BOOT_COMPLETED" = "1" ]; then
           echo "Android emulator is ready!"
           break
          fi

          sleep 5
          done
          
          adb devices
          
          echo "===== Emulator Log ====="
          cat emulator.log

      - name: Start Appium server
        run: |
          nohup appium --address 127.0.0.1 --port 4723 > appium.log 2>&1 &
          sleep 5
          curl http://127.0.0.1:4723/status

      - name: Run Maven tests
        run: mvn test